export enum ActionType {
    AUTO_COMPLETE = "AUTO_COMPLETE",
    RESET_AUTO_COMPLETE = "RESET_AUTO_COMPLETE",
    GET_CURRENT_CONDITIONS = "GET_CURRENT_CONDITIONS",
    UPDATE_CURRENT_PLACE = "UPDATE_CURRENT_PLACE",
    SAVE_TO_LOCAL = "SAVE_TO_LOCAL",
    ADD_CLASS_ANIMATIONS_FAVORITE_LINK = 'ADD_CLASS_ANIMATIONS_FAVORITE_LINK'
}