export const ACCUWEATHER_API_KEY = 'fAqebVmH2xdABat6sLyLFr0MoZuQwrTh';
export const INIT_CITY_CODE = '215854';
export const INIT_CITY_NAME = 'Tel Aviv';
export const LOCAL_KEY = 'weather';
export const ERROR_API = "This API is limited to 50 requests per day, all you need is generate a new hash code and put it in coomon/consts/strings and switch => ACCUWEATHER_API_KEY";
export enum WeatherIcons {
   'http://vortex.accuweather.com/adc2010/images/slate/icons/01.svg' = 1,
   'http://vortex.accuweather.com/adc2010/images/slate/icons/02.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/03.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/04.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/05.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/06.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/07.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/08.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/09.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/10.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/11.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/12.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/13.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/14.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/15.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/16.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/17.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/18.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/19.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/20.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/21.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/22.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/23.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/24.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/25.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/26.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/27.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/28.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/29.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/30.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/31.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/32.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/33.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/34.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/35.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/36.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/37.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/38.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/39.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/40.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/41.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/42.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/43.svg',
    'http://vortex.accuweather.com/adc2010/images/slate/icons/44.svg',
}